F_CPU = 8000000
BOOTLOADER_SIZE = 4096

OPT_DEFS += -DINTERRUPT_CONTROL_ENDPOINT
OPT_DEFS += -DPROTOCOL_BLE
OPT_DEFS += -DUART_RX1_BUFFER_SIZE=128 -DUART_TX1_BUFFER_SIZE=256
OPT_DEFS += -DUSART1_ENABLED

SRC += 	../usart.c \
		../ch5x2.c \
        ../main.c